site_name: Csound Plugins
# theme: readthedocs
theme: 
    name: readthedocs
    highlightjs: false
    prev_next_buttons_location: none
    navigation_depth: 1
    
extra_css:
    - css/syntax-highlighting.css
    
markdown_extensions:
    - codehilite:
        guess_lang: false
        use_pygments: true
    - admonition

use_directory_urls: false
